services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"   # HTTP-интерфейс ClickHouse
      - "9000:9000"   # Нативный интерфейс ClickHouse
    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin
      - CLICKHOUSE_LOG_LEVEL=debug
    volumes:
        - ./clickhouse/data:/var/lib/clickhouse
        - ./clickhouse/config/http.xml:/etc/clickhouse-server/config.d/http.xml
        - ./clickhouse/logs:/var/log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"  # Максимальный размер файла лога
        max-file: "3"    # Количество файлов, после которого логи будут перезаписываться
    networks:
      - xcvzv97opkje
    healthcheck:
      test: [ "CMD", "clickhouse-client", "-u", "admin", "--password", "admin", "--query", "SELECT 1" ]
      interval: 5s
      timeout: 3s
      retries: 20

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
    depends_on:
      - clickhouse
    volumes:
      - ./grafana/data:/var/lib/grafana  # Сохраняем данные Grafana на хосте
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - xcvzv97opkje

  vector:
    image: timberio/vector:0.36.0-debian
    container_name: vector
    command: ["-c", "/etc/vector/vector.toml"]
    volumes:
      - ./vector/vector.toml:/etc/vector/vector.toml:ro
      - ./vector/logs:/var/log/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      clickhouse:
        condition: service_healthy
    networks:
      - xcvzv97opkje

  logg_emulator_one:
    image: "python:3.11"
    container_name: "logg_emulator_one"
    working_dir: "/app"
    command: [ "/bin/sh", "-c", "pip install -r /app/requirements.txt && export PYTHONPATH=/app && python main.py" ]
    volumes:
      - ./requirements.txt:/app/requirements.txt
      - ./main.py:/app/main.py
      - ./improved_logging:/app/improved_logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  logg_emulator_two:
    image: "python:3.11"
    container_name: "logg_emulator_two"
    working_dir: "/app"
    command: [ "/bin/sh", "-c", "pip install -r /app/requirements.txt && export PYTHONPATH=/app && python main.py" ]
    volumes:
      - ./requirements.txt:/app/requirements.txt
      - ./main.py:/app/main.py
      - ./improved_logging:/app/improved_logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  xcvzv97opkje:
    external: true