[sources.emulators]
type = "docker_logs"
include_containers = ["logg_emulator_one"]

[sinks.clickhouse]
type = "clickhouse"
inputs = ["emulators"]
endpoint = "http://clickhouse:8123"
database = "default"
table = "logs"
auth.user = "admin"
auth.password = "admin"
auth.strategy = "basic"
healthcheck.enabled = true
healthcheck.timeout_secs = 30