# Источник логов — файлы контейнеров
[sources.container_logs]
type = "file"
include = ["/var/log/containers/*.log"]
ignore_older = 86400  # игнорировать файлы старше 1 дня

# (Опционально) Преобразование: попытка разобрать JSON, если логи в формате JSON
[transforms.parse_json]
type = "json_parser"
inputs = ["container_logs"]
drop_invalid = true

# Синк для ClickHouse
[sinks.clickhouse]
type = "clickhouse"
inputs = ["parse_json"]
endpoint = "http://clickhouse:8123"   # адрес сервера ClickHouse (изнутри кластера)
database = "default"                  # имя базы данных
table = "logs"                        # имя таблицы, куда будут записываться логи
compression = "gzip"                  # (опционально) сжатие
batch.max_bytes = 10485760
batch.timeout_secs = 1
auth.user = "admin"
auth.password = "admin"
