[sources.emulators]
type = "docker_logs"
include_containers = ["logg_emulator_one"]

# Синк для ClickHouse
[sinks.clickhouse]
strategy = "insert"
type = "clickhouse"
inputs = ["emulators"]
endpoint = "http://clickhouse:8123"
database = "default"
auth.user = "admin"
auth.password = "admin"
table = "logs"
compression = "gzip"
batch.max_bytes = 10485760
batch.timeout_secs = 1
